[project]
name = "UBT Discord Bot"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "requests>=2.32.3",
]
